- hosts: 192.168.29.219
  tasks:
  - yum_repository:
       baseusrl: "http://download.docker.com/linux/centos/7/x86_64/stable/"
       name: "docker_dvd"
       description: "docker package"
       gpgcheck: no

  - package:
       name: "docker-ce-18.09.1-3.el7.x86_64"
       state: present

  - package:
       name: "python3"
       state: present

  
  - service:
       name: "docker"
       state: restart
       enable: yes
